### ISSUE TITLE
Vinary bug

### ISSUE THREAD

**Issue by MalachiAzrael** [katubug/CottageWitch119#11]
When shift clicking items in the Vinary Rustic Cooking Pot, instead of leaving the inventory, they just move slots and dupe.

**Comment by katubug** [comment]
Thanks for reporting! This was already reported at their issue tracker, but I've bumped the thread: https://www.curseforge.com/minecraft/mc-mods/lets-do-wine/issues/77

**Comment by MalachiAzrael** [comment]
Awesome, just wanted to make you aware

**Comment by satisfyu** [comment]
Dont u like infinite netherite? x3 

It's being worked on atm - fix should be out soon

**Comment by katubug** [comment]
Lol! Thank you for the update
