### ISSUE TITLE
Seagulls should not steal lunchboxes

### ISSUE THREAD

**Issue by rmonk** [katubug/CottageWitch119#12]
Since Spice of Life lunchboxes look tasty to seagulls, getting near them can result in losing all your food without even knowing it, then they are gone and eat it before I can even find them.  I go into the mod settings and just disable seagull stealing, but maybe the lunchboxes should be in the seagull ignore list instead just to stop the frustration?  I can just murder all the seagulls I see on sight, but that doesn't seem very witchy 😆 

I've been caught by this now three times.  First time I had no idea what happened, second time I noticed and disabled stealing, third time was after I updated and the Alex's Mods config was reset.

**Comment by katubug** [comment]
I could have sworn I already did this, but we definitely have been having issues with the config resetting, even on my end. This will be included in the 1.12.2 update!

**Comment by katubug** [comment]
Fixed!
