### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by Ramen-nerd** [katubug/CottageWitch119#13]
so I have this problem, I'm using the most recent release, and everything seems to work as intended, the game loads, and I even have a functioning menu, but the moment I get to the preparing world screen the game crashes, I don't know what the issue is, I've tried uninstalling and then reinstalling, and even tried messing around with the settings, but it just keeps crashing. and its not a problem with Minecraft itself I don't think, I checked and vanilla works fine. sorry to bother you but id like some assistance on this matter

**Comment by katubug** [comment]
Hi, do you get a crash report with this? It'd be inside the modpack
instance directory, inside the crash-reports folder.

If you have that, please upload the most recent one.

If not, make sure you've allocated enough RAM to the pack via Curseforge.

**Comment by Ramen-nerd** [comment]
im so terribly sorry to bother you but where do i find the crash report folder? ive opened the files and cant seem to find one

**Comment by katubug** [comment]
Assuming you're using CF launcher:

If you hit the three dots next to play and choose "open folder," that will
open the instance directory. If there's nothing in there called
"crash-reports" then you don't have any full crashes.

In the lower left of the launcher there's a settings gear. Click that, then
click on "Minecraft" on the left. Scroll down in the middle until you see
Java settings. Move the slider until 6-8gb is allocated. Then try launching
the game again.

**Comment by Ramen-nerd** [comment]
ok i gave it about 6gbs but it still crashed, sorry

**Comment by katubug** [comment]
Aww it's fine! You're definitely not stupid for assuming that "not
responding" means what it says. That's a perfectly reasonable thing to
expect. It's just a quirk of modded mc that it doesn't act like you'd
expect. So shush, and you're very welcome! Have a great day :)
