### ISSUE TITLE
Crash after opening or creating any new world

### ISSUE THREAD

**Issue by cassieistoodah** [katubug/CottageWitch119#15]
Hey, I use this modpack a lot and got the recent update yesterday afternoon and it was working fine all night and I tried to get back on this morning and none of my previous worlds would open and it wouldnt create a new world as I'd be on the loading world page for 10-30 minutes until it just shut down. I hadn't changed anything else after playingh last night so I am a bit confused and hope you can help me out lol
[launcher_log.txt](https://github.com/katubug/CottageWitch119/files/11191078/launcher_log.txt)

**Comment by katubug** [comment]
I'm not sure what could be causing this. Can you attach your latest.log? You can find that in your /logs/ folder of the modpack instance. Unfortunately the launcher log doesn't have the information I need.

**Comment by cassieistoodah** [comment]
[crash-2023-04-10_12.31.16-server.txt](https://github.com/katubug/CottageWitch119/files/11215376/crash-2023-04-10_12.31.16-server.txt)
sry didnt realize i had the wrong one, i hope this is the right one
