### ISSUE TITLE
[Crash] BYG Sapling Crash

### ISSUE THREAD

**Issue by katubug** [katubug/CottageWitch119#18]
**What Cottage Witch version are you using?**
Version: 1.13.1

**Link to reported issue:**
https://github.com/AOCAWOL/BYG/issues/1142

**Comment by CorgiTaco** [comment]
Seems the block in question is unknown in the game registry as it cant retrieve the id for the block? Seems possible a block is registered without an id ie "minecraft:oak_sapling".... I'd recommend deleting the `growing-patterns.json5` config and restarting the game to have it regen.
