### ISSUE TITLE
Forage Wild Crops Quest

### ISSUE THREAD

**Issue by Zolexa13** [katubug/CottageWitch119#2]
The Forage Wild Crops quest (1st one under Gathering) is not recognizing when you break Wild Cabbage.  The quest item looks to be pointing to "block.farmersdelight.wild_cabbage" (different from the rest of the wild crops) and is not accecpting when you break them in the world.

**Comment by katubug** [comment]
Thanks so much for catching and reporting this! I really appreciate you taking the time to make these two issues :)

I've fixed this in 1.6, which will be out later today. Thanks again!
