### ISSUE TITLE
Mob Container Quest Reward Glitch?

### ISSUE THREAD

**Issue by Sarafimm** [katubug/CottageWitch119#20]
Playing the recently updated game last night, April 13th, 1.19-1.13.1. version.  I believe there is a quest reward that needs to be updated.  Wildlife Quest; Pets & Livestock; Advancement BFF (lead) reward:  I got the companion cube and cow plushie, but the FTBQuests "mobcatcher:net" is listed as a Missing Item.  It was just an unknown icon type of thing with a big question mark.  Wondering if it should be a Cage (supplementaries:cage), Jar (supplementaries;jar), Containment Jar (ars_nouveau:mob_jar), or something else.

**Comment by katubug** [comment]
Thanks, you're right! I removed the broken reward, but I didn't add a new
one. I think a Cage is a great idea, so I'm leaving this ticket open until
I fix that.

**Comment by katubug** [comment]
This will be fixed in the next update.
