### ISSUE TITLE
Zombie villagers lack textures

### ISSUE THREAD

**Issue by An12854** [katubug/CottageWitch119#26]
**What Cottage Witch version are you using?**
Version: 1.13.3

**How much RAM you have allocated (recommended 6-8gb)**
8GB

**Clearly describe the issue**
Zombie villagers lack textures

**Screenshots**
![villager 1](https://user-images.githubusercontent.com/50544887/233357667-6fa8f23b-69bf-4706-bdd5-49a7b05a469e.png)

![villager 2](https://user-images.githubusercontent.com/50544887/233357691-0a7e918e-50fb-4703-ba39-36160406edf5.png)

**Comment by katubug** [comment]
Hi, have you added or removed any mods to the modpack? And does this persist if you restart your game?

**Comment by An12854** [comment]
Sorry for the wait, no i haven't messed with mods, it's a recently installed modpack, and the issue persists on restart

![image](https://user-images.githubusercontent.com/50544887/234569534-99ae40b9-a980-49c1-a53b-a1e98ae4463c.png)

**Comment by katubug** [comment]
No worries! Are you able to tell what mod they're from? My guess is that
perhaps the Chef's Delight or Villagers Plus mod doesn't properly add
zombie textures for their villager professions. You may want to report it
to one of them, as this isn't something within my power to fix. Thanks for
the report though!
