### ISSUE TITLE
[Crash] Attempting to make pickles

### ISSUE THREAD

**Issue by frootbirb** [katubug/CottageWitch119#27]
**What Cottage Witch version are you using?**
Version: 1.13.3

**What were you doing when you crashed?**
Attempted to make pickles by the JEI recipe (four cucumbers in a fermenting barrel with 1 heat)
Note: this does not reproduce on single player.

**To Reproduce**
1. Drag four pickles over the GUI of a fermenting barrel
2. Observe crash

**Crash Reports or Latest.log**
[crash-2023-04-21_19.38.04-server.txt](https://github.com/katubug/CottageWitch119/files/11299826/crash-2023-04-21_19.38.04-server.txt)

**Comment by katubug** [comment]
Hi, can you please report this to the mod authors? Unfortunately this is an
issue with solely their mod and I'm not able to do anything about it.
