### ISSUE TITLE
Miscellaneous > Commerce Quest

### ISSUE THREAD

**Issue by Zolexa13** [katubug/CottageWitch119#3]
The Trade with a Villager Quest does not appear to be updating if you traded with a villager and received the achievement (What a Deal!) prior to unlocking the quest in the book. Additional trades do not update the quest.

**Comment by katubug** [comment]
Now that's a weird one! You should automatically get all advancement quests
even retroactively. I'll test it out and see what I can find. Thank you!

**Comment by katubug** [comment]
I haven't been able to replicate this, I'm very sorry. I haven't had any additional reports, so I'm going to close this for now.
