### ISSUE TITLE
[Bug] Dupe involving MouseTweaks and Quark's backpack

### ISSUE THREAD

**Issue by Bluberry-Kat** [katubug/CottageWitch119#31]
**Describe the bug**
Using MouseTweaks scrolling feature to move items from Quark's backpack to the player's inventory will duplicate the item being scrolled.

**To Reproduce**
1. Open Inventory
2. Equip Backpack
3. Place any (stackable, I think) item in backpack
4. Attempt to "scroll" item out
5. Item will be "moved" to the inventory, but simultaneously remain in the backpack, duplicating it.

**Expected behavior**
Item should move from backpack to player's inventory uneventfully.

**Screenshots**  

https://user-images.githubusercontent.com/20749209/234686609-8c923a1f-3fe9-4ce3-b26a-0d3112c1278b.mp4

**What Cottage Witch version are you using?**
Version: 1.14.0a
 
**Additional context**
I reported this here as it's a conflict between two mods and I'm not yet sure which it ought to go to.  
I figure this issue can be linked in either mods' repo for context regardless.

**Comment by katubug** [comment]
Hi, yeah I think this would be a good one for Quark, might be Quark
Oddities specifically. Although honestly I'm a little surprised that there
isn't already compatibility between them as they're both fairly major mods.
I wonder if there's another issue here, like latency? But definitely I'd
recommend reporting it to Quark.
