### ISSUE TITLE
[Bug] Death marker glow stays on

### ISSUE THREAD

**Issue by An12854** [katubug/CottageWitch119#33]
**Describe the bug**
The death marker disappears but the glow stays

**To Reproduce**
1. Die
2. Go to death point
3. Pick up your stuff on the grave

**Expected behavior**
That the death marker glow would disappear too when picking up your stuff

**Screenshots**
![2023-04-27_16 07 51](https://user-images.githubusercontent.com/50544887/234905697-a6a2ef39-bd5b-419a-9f87-a8a6e7c4fcc9.png)

**What Cottage Witch version are you using?**
Version: 1.13.3

**Additional context**
i went to pick up the stuff in my grave, when i picked it up the death marker disappeared but the glow stayed, and yes it persists upen restart

**Comment by katubug** [comment]
Hi, this is an issue with FTB chunks. There is a tutorial quest in the
first category to explain how to disable them.

**Comment by An12854** [comment]
Forgot about it, sorry
