### ISSUE TITLE
[Bug] 'ultraburgercon' recipe possible typo

### ISSUE THREAD

**Issue by brisingraerowing** [katubug/CottageWitch119#35]
**Describe the bug**
[This recipe](https://github.com/katubug/CottageWitch119/blob/main/scripts/general.zs#L362-L367) outputs a deluxe cheeseburger, but requires a deluxe cheeseburger as input. Was the input supposed to be a regular cheeseburger?

**To Reproduce**
Issue in code

**Expected behavior**
Recipe doesn't require the item it outputs

**Screenshots**

**What Cottage Witch version are you using?**
Version: noticed on GH

**Additional context**
Was randomly perusing the code for ideas and noticed that.

**Comment by katubug** [comment]
Whoops! Good catch, thank you!

**Comment by brisingraerowing** [comment]
NP! I've done the same thing myself a few times. Autocomplete can be a pain sometimes.
