### ISSUE TITLE
No Hands

### ISSUE THREAD

**Issue by TinaLuwten** [katubug/CottageWitch119#36]
**What Cottage Witch version are you using?**
Version: 1.19

**How much RAM you have allocated (recommended 6-8gb)**
5G
**Clearly describe the issue**
I dont have any hands and there is also no indication im breaking or using blocks other then the here's what your looking at interface. the modpack runs smooth as butter and i want to play it but not having hands is a little weird, maybe this is a problem with my settings but i still feel like i should bring it up

**Screenshots**
![2023-05-18_14 33 09](https://github.com/katubug/CottageWitch119/assets/134014546/ed79dba9-43bd-42c6-a1c6-9cebd46793dc)

.

**Comment by TinaLuwten** [comment]
Update to this issue i cant see myself at all even in F5 i just dont exist

**Comment by katubug** [comment]
This is a known issue, I thought I'd put it in the issues but I guess I
didn't!

Restarting your client will fix the issue. I'll leave this ticket up for
future users :)

**Comment by TinaLuwten** [comment]
thank you!
