### ISSUE TITLE
[Suggestion] ModernFix

### ISSUE THREAD

**Issue by xJon** [katubug/CottageWitch119#38]
You should definitely consider adding [ModernFix](https://www.curseforge.com/minecraft/mc-mods/modernfix). Using the mod cuts the loading time until reaching a world by about half which really positively affects the experience of playing the pack :) It also has some other benefits and is actively being developed.

Beyond that, I also noticed you mention in the description you're using Canary but it's been removed in v1.13.1. It has since been updated multiple times so you can consider re-adding it, or if you chose to keep it out then update the description accordingly.

**Comment by katubug** [comment]
I'm sorry for not responding to this! I did actually see it, and did add Modernfix per your suggestion. So thank you for that, and my apologies for the very late reply.
