### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by sneezingserapis** [katubug/CottageWitch119#39]
hello, i've been trying to launch the pack for about the last hour or so through the curseforge app, but every time it gets past the initial install the launcher crashes. at first i thought that i had maybe downloaded the wrong version, but after trying a couple i don't think that's the issue. i've tried top update some of my drivers too, as i saw a past report that mentioned that, but so far no luck.

some help would be greatly appreciated!

[latest.log](https://github.com/katubug/CottageWitch119/files/11632056/latest.log)

**Comment by katubug** [comment]
Have you allocated at least 6gb of RAM through curseforge?

**Comment by sneezingserapis** [comment]
just tried that, no luck.

[latest.log](https://github.com/katubug/CottageWitch119/files/11637475/latest.log)

**Comment by katubug** [comment]
That's weird, I don't see any crash stacktraces. Have you added any mods to
the pack? I see some references to things which aren't in the modpack, but
I'm not sure why.

**Comment by sneezingserapis** [comment]
that's so strange, i don't think i've added anything? could you maybe be more specific so i could be sure?

**Comment by katubug** [comment]
You know what, scratch that. Now that I've looked at the log, I realize
that what I'm seeing are included mods disabling compatibility for mods
which aren't present, which is as it should be.

I'm not seeing anything that indicates why it's crashing though. Usually
that's a RAM thing, and I don't see a specific RAM allocation argument in
the log, do you have it set in the general CF Minecraft section, or by
profile?

**Comment by sneezingserapis** [comment]
i've tried allocating more ram through both. would it help if i sent the crash report that shows up whenever it happens? i would do it here, but i can't think of a more concise way to share it without just pasting the whole thing here, which would be a formatting nightmare (especially if there's no use in sharing it in the first place).

**Comment by katubug** [comment]
The crash report would definitely help! You can upload the contents onto
pastebin.com and then send the link here

**Comment by sneezingserapis** [comment]
here you go!

https://pastebin.com/ejE5GB8d

thank you so much for all your help, hope this works!

**Comment by katubug** [comment]
I'm so sorry I never got back to this! I'm discovering a whole bunch of issues where github didn't send me an email for it, and I feel quite bad.

I know this is quite a long time ago, now, but the issue was to do with your AMD gpu drivers. Hopefully you were able to remedy it!
