### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by failedartkid** [katubug/CottageWitch119#41]
**What Cottage Witch version are you using?**
Version: 1.19-1.14.5

**What were you doing when you crashed?**
A clear and concise description of what happened.
-I was just placing spruce planks, though I've had previous crashes where I was doing something entirely different when the game crashed. I'm sorry I don't have more helpful information, I just have had the game randomly crash on me in a variety of situations and I haven't been able to determine a clear reason why, which is why I'm submitting this report.
**To Reproduce**

**Screenshots**

**Crash Reports or Latest.log**
Drag and drop your latest.log and/or crash report here, or paste a pastebin.com or gist.github.com link with their contents. To find these files (assuming CurseForge launcher), click the 3 dots next to the Play button and choose "Open Folder." Logs are in the /logs/ folder, and crashes are in /crash-reports/. *These files are often CRUCIAL to diagnosing your issue, so please include them.*
[](url) [hs_err_pid27844.log](https://github.com/katubug/CottageWitch119/files/11644486/hs_err_pid27844.log)

**Additional context**
I do have two additional mods installed, and I did have up update both Xaero's Minimaps and Xaero's World Map, but I have been experiencing random crashes prior to installing those mods and updates and they haven't increased in frequency since doing so.

**Comment by katubug** [comment]
Hi! So this looks like it might be an issue with AMD drivers, is your
graphics card AMD? If so, we have a thread in our discord with
troubleshooting steps which have helped others. I'm on mobile ATM so I
can't copy them over easily. Sorry for the trouble.

**Comment by failedartkid** [comment]
Hi, it looks like I have NVIDIA graphics card rather than AMD, will I still
be able to find troubleshooting tips in the server? Thanks for working to
help me figure this out, I appreciate it!

**Comment by katubug** [comment]
If you have Nvidia, it might just be that you need to update some drivers!
I'm not sure whether it's Java or GPU drivers that need updating, but
definitely if you pop into the tech-support channel in discord we can help
you out in real time! :)
