### ISSUE TITLE
Getting Exit code 1 error with 1.19-1.14.9

### ISSUE THREAD

**Issue by Fade-Alchemist** [katubug/CottageWitch119#42]
**What Cottage Witch version are you using?**
Version: 1.19-1.14.9

**How much RAM have you allocated (recommended 6-8gb)**
You can check this by viewing your launcher's settings. If you do not have 6 GB allocated, please try this first.

I am using 8 GB of Ram

**Clearly describe the issue**

I launch the game as normal from Forge and it begins to load - but it crashes out before I reach the Minecraft menu to "Exit code 1". No crash report was generated, but I did include my log file - in case that would be helpful. Screen shots of my Java version and GeForce drivers are included (both were updated yesterday)

**Screenshots**

![fc2d630c-b79a-4da6-92c1-fe0492ea40c4](https://github.com/katubug/CottageWitch119/assets/29619427/ef15616e-2f6d-402a-aec2-4c3be0d1860f)
[2023-06-07-2.log.gz](https://github.com/katubug/CottageWitch119/files/11672857/2023-06-07-2.log.gz)
[latest.log](https://github.com/katubug/CottageWitch119/files/11672910/latest.log)

![image](https://github.com/katubug/CottageWitch119/assets/29619427/b8ae5a05-1cbe-4e4a-87b9-b13d5a6e41fd)
![image](https://github.com/katubug/CottageWitch119/assets/29619427/8c9bbf0b-8f0e-4813-be41-55dacc1fd3f0)

**Comment by Fade-Alchemist** [comment]
Update: I just tried to launch a 1.19.2 Forge world sans mods, to eliminate my PC as a problem. It launched with no errors.

**Comment by Fade-Alchemist** [comment]
Figured it out - I needed to run a repair of the Minecraft launcher 
![image](https://github.com/katubug/CottageWitch119/assets/29619427/cc6c6fbc-bcdb-4e0b-b7f1-8f98eba5eb36)

After doing so you need to launch the vanilla launcher and restart it for it to update - then try the forge instance again and it should work,

**Comment by katubug** [comment]
My apologies, I never got the email about this issue. However, I would have been little help anyway, since the issue was not with the pack itself, but with the Curseforge installation. I am glad you were able to figure it out.
