### ISSUE TITLE
Forgiveness allows infinite duping via stairs/fences

### ISSUE THREAD

**Issue by ironsnake345** [katubug/CottageWitch119#43]
**What Cottage Witch version are you using?**
Version: 1.15.2hotfix

**How much RAM you have allocated (recommended 6-8gb)**
About 6.5 GB

**Clearly describe the issue**
Forgiveness adds recipes for converting stairs and fences back into their respective blocks, for stones and woods. That's all well and good, but the problem is that it doesn't account for high-efficiency versions of those recipes enabled via the stonecutter or woodcutter. One block can be put in its matching cutter to turn it into one stair, or one fence if it's made of wood, and then two stairs can be combined into three of the matching block, or three fences (not walls) into five of the matching block.

I understand that this is a pretty softcore experience, but being able to infinitely dupe blocks by sawing and unsawing them repeatedly kind of undermines the fun of finding a way to produce infinite andesite for the Create mod, or cultivating rare trees for Hexerei, or hunting down rare building materials for extra fancy brick types like purpur bricks or red nether bricks.

I'm totally in favor of being able to turn stairs back into bricks, I just don't think that also duplicate the bricks infinitely.

**Comment by katubug** [comment]
This is definitely not intended, just a mod interaction that I didn't
catch. Thank you for reporting! We'll get this sorted out.

**Comment by katubug** [comment]
I looked into this, and unfortunately there was simply no way to fix it that didn't involve hours of work, so we decided to remove Forgiveness. It was already on the list of mods to potentially cut, so this was just the last nail in the coffin. Thanks for the report! Fixed in 1.15.3
