### ISSUE TITLE
Crash when launching 

### ISSUE THREAD

**Issue by lobster09000** [katubug/CottageWitch119#44]
**What Cottage Witch version are you using?**
Version: 1.15.2 hotfix

**How much RAM you have allocated (recommended 6-8gb)**
You can check this by viewing your launcher's settings. If you do not have 6gb allocated, please try this first.

maximum RAM allocated via curseforge

**Clearly describe the issue**
Describe what is happening and what you are doing when and after it happens. For example, if your game goes "Not Responding" while loading (which is normal btw), are you clicking on the window? Are you letting it load? Do you have a lot of background processes? etc.

I click the play button via curseforge, the modpack installs, and when it attempts to actually play or load the game, I receive an Exit Code 1 crash. This has been happening for the last 3 days as i've attempted to play, i've updated my graphics card and drivers, and i've reinstalled the launcher for curseforge. 

I've never played this modpack before, and i do not have Forge installed on it's own. 

Playing vanilla minecraft or other modpacks via curseforge on 1.19.2 work just fine, this modpack is the only issue i'm having. 

**Screenshots**
Attach relevant screenshots here.
![image](https://github.com/katubug/CottageWitch119/assets/138023085/d735b208-0bb0-418b-ba7c-cff0712260f5)

**Comment by katubug** [comment]
Hi, two things! Firstly, what is the numerical amount of RAM you have
allocated? More than 8gb or less than 6gb can cause issues.

Secondly, can you please attach your most recent crash report? The exit
code doesn't tell me anything.

Thanks!
