### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Zebbycorn** [katubug/CottageWitch119#45]
**Describe the bug**
After updating and joining single player all of my progression in quests reset

**To Reproduce**

**Expected behavior**

**Screenshots**

**What Cottage Witch version are you using?**
Version: 1.15.3fixzip

**Additional context**
this happens when I update

**Comment by katubug** [comment]
Can you tell me more about the update? Which version did you update from, and did you update to a new profile?

It's possible your quest progress file got corrupted, but I'm not sure how. Thankfully, you should be able to restore from backup, by unzipping the world in your /backups/ folder.
