### ISSUE TITLE
[Bug]Cheeseburger annd Deluxe Cheeseburger

### ISSUE THREAD

**Issue by RamenInACupboard** [katubug/CottageWitch119#46]
The Cheeseburger and Deluxe Cheeseburger both only give one diversity contribution despite the normal Hamburger giving 5.

It should probably give a lot more I'm assuming?

Version: 1.15.3fix

**Comment by sigmastar00** [comment]
Thank you for reporting! We have a big food rework in progress that should fix this and similar issues.
