### ISSUE TITLE
[Bug]Deluxe Cheesebuger Recipe

### ISSUE THREAD

**Issue by RamenInACupboard** [katubug/CottageWitch119#47]
A Deluxe Cheeseburger crafts into a Deluxe Cheeseburger? 

I think it's supposed to be a Cheeseburger that crafts into that

**Comment by katubug** [comment]
Which version are you playing on? This was supposed to be fixed a version or two ago

**Comment by RamenInACupboard** [comment]
im using aternos perhaps thats why?

**Comment by katubug** [comment]
I don't know anything about how aternos does their modpacks, but the most
recent version is 1.15.5, so if you can update, I'd recommend it!

**Comment by RamenInACupboard** [comment]
Aternos automatically updates the pack, so I suppose it's just an issue
there I suppose. Oh, and is there a place to make suggestions?

**Comment by katubug** [comment]
You were right, by the way. We somehow managed to edit the wrong recipe. It's fixed now though! Thank you for reporting.
