### ISSUE TITLE
[Bug] Fairy Lights recipes do not work

### ISSUE THREAD

**Issue by bylolove** [katubug/CottageWitch119#48]
**Describe the bug**
When trying to craft items from the Fairy Lights mod on a crafting table (I have not tried with the BYG variants), most of the items do not craft. The only item I found that I was able to craft was the Incandescent Light, but I can't use them in the recipe to make string lights. This happened with both using the JEI crafting shortcut and placing each item individually into the crafting grid. 

_JEI recipe_
![Imgur](https://i.imgur.com/Y4GFv5u.png)

_Recipe in crafting table_
![Imgur](https://i.imgur.com/7jfVNfb.png)

Also, this happened after restarting the game, but now the pop-up saying "**Craft hanging lights** The recipe book can help" is perpetually stuck in the top right corner. 

_Pop-up_
![Imgur](https://i.imgur.com/5ehFTbI.png)

**What Cottage Witch version are you using?**
Version: 1.15.5.zip

**Additional context**
I've tried making a new world to see if my world was corrupted in some way and the recipes still haven't worked. I have not tried reinstalling the modpack in Curseforge.

**Comment by katubug** [comment]
Hi, this an issue with the Fairy Lights mod itself and would be better
reported to them! Sorry that there's not really anything I can do on my
end. :(
