### ISSUE TITLE
Cupboard 1.2 Dependency Missing in Latest Server Pack

### ISSUE THREAD

**Issue by JibGold** [katubug/CottageWitch119#49]
**What Cottage Witch version are you using?**
Version: 1.15.6

**Clearly describe the issue**
The mod "Clickable Advancements" requires Cupboard V1.2 to be installed in order to run the server. At present, the server pack on CurseForge does not have this dependency installed natively, so the startserver.bat file gets stuck in an infinite crash loop due to this missing dependency.

**Comment by katubug** [comment]
I'm sorry I never responded to this! I have a crap memory. Thank you for reporting!
