### ISSUE TITLE
Pocket Money (No Drops) 1.04 Missing on Client Version of Modpack

### ISSUE THREAD

**Issue by JibGold** [katubug/CottageWitch119#50]
**What Cottage Witch version are you using?**
Version: 1.15.6

**Clearly describe the issue**
The server pack contains a mod titled "Pocket Money (No Drops)" but the client does not have this mod installed which prevents players from logging in to servers created using the server pack.

**Screenshots**
![image](https://github.com/katubug/CottageWitch119/assets/116314329/bcece5ff-cc80-4547-88c7-3277ff7a431d)

**Comment by katubug** [comment]
Hi, thanks for both reports! We will get a new version uploaded ASAP, but
CurseForge is now taking up to 2-3 days to approve updates, so in the
meantime I recommend manually changing the files. Sorry for the
inconvenience! Thanks again

**Comment by JibGold** [comment]
No worries! Totally understand.
For what it’s worth, myself and some other players were able to add the missing mod to the player client, but for some reason the server still refused to allow players to log in.

Did try to reset the server’s config folder since, according to some mentions online, disparity between client and server configs apparently can cause this error alongside mod folder disparities. While it did allow me to log in for a few moments and see the surrounding spawn environment, the server seems to continue to boot players even after adding the missing mod on the client side and adding the missing dependency on the server side.

For what it’s worth, I haven’t checked to see if the KubeJS folders are consistent between client and server, but considering the extended delay between login and booting after adding the missing client mod that would be typical of KubeJS loading the contents of its folders and the fact that the missing mod on player clients is (from what I understand) KubeJS adjacent, that might be the culprit here.

Planning on making those changes this morning. Will update here if that solves the issue.

**Comment by JibGold** [comment]
It turns out my nonexistent KubeJS skills are more nonexistent than I assumed. I'll leave all the KubeJS stuff up to the professionals. lol. Of note, though, if this is a concern: kubejs's "assets" folder was empty on the server.

**Comment by katubug** [comment]
That is intended! The assets are client side only.

To connect, you'll want to delete pocket money from both client and server,
as well as change the server's Cupboard to versions 1.2. I wasn't sure if
you fixed both issues, but that should do it! Also if you haven't, you'll
want to restore the server side and client configs to default, as there are
a lot of changes that the modpack might function weirdly without. :)

**Comment by JibGold** [comment]
Gotcha.

I'll see what I can sort out with the client and server pocket money deletion process.

At the moment, after resetting the server files back to default, adding he Cupboard version 1.2 mod dependency, and renaming the Forge launcher file per my host's requirements, I was able to join the server just fine.

I'll give deleting pocket money from the client and server a shot here and see if the server still works.

**Comment by katubug** [comment]
Sorry, I should have said it's actually fine to keep your pocket money
files in place as long as both client and server have them! It won't hurt
anything.

**Comment by JibGold** [comment]
I think I understand your meaning. 

If I'm understanding you correctly, I assume Pocket Money was not supposed to be included in this version of the server files according to the changelog comment about how "This update removes Pocket Money." Having both files installed on client and server isn't required for the pack to function, but if the mods are installed on both client and server, they shouldn't cause issues.

Thanks for the help! Appreciate you taking the time to chat about the issue. :)
