### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by GivingWings169** [katubug/CottageWitch119#51]
**What Cottage Witch version are you using?**
Version: 
1.15.6

**What were you doing when you crashed?**
A clear and concise description of what happened.
Trying to launch the game

**To Reproduce**
Click launch. It crashes.

**Screenshots**

**Crash Reports or Latest.log**
Drag and drop your latest.log and/or crash report here, or paste a pastebin.com or gist.github.com link with their contents. To find these files (assuming CurseForge launcher), click the 3 dots next to the Play button and choose "Open Folder." Logs are in the /logs/ folder, and crashes are in /crash-reports/. *These files are often CRUCIAL to diagnosing your issue, so please include them.*

**Additional context**
[hs_err_pid6616.log](https://github.com/katubug/CottageWitch119/files/12208703/hs_err_pid6616.log)

**Comment by katubug** [comment]
This is an issue with AMD video card drivers. Our discord has information
about troubleshooting this issue, or you can try googling. Thanks for
reporting!
