### ISSUE TITLE
[Bug] funcMissingModel on Quest "Mushroom Hat"

### ISSUE THREAD

**Issue by Luxzhv** [katubug/CottageWitch119#53]
**To Reproduce**
Navigate to questbook, Beginnings > Freebies > Mushroom Hat and collect item from quest.

I expected the pumpkin to be a totally different model when equipped.

**Screenshots**

![image](https://github.com/katubug/CottageWitch119/assets/10239215/3796ed00-e7e3-493a-9120-8b89b9443e79)

I am using Cottage Witch 1.15.7

I think this can be fixed by having proper model data packed somewhere, or relinked.

**Comment by katubug** [comment]
Hi, do you have all the resourcepacks enabled? That's what turns the
pumpkin into there mushroom hat.

**Comment by Luxzhv** [comment]
Investigating now, Resourcepack might be disabled by default.

**Comment by Luxzhv** [comment]
Anyway, thanks again, what would be the recommend resourcepack order, so I and others don't get any additional texture conflicts.

**Comment by katubug** [comment]
Unfortunately resourcepacks not being enabled by default is a bug that has
persistently eluded us! The only way to definitely prevent it is to include
the options.txt in the pack, which would reset everyone's keybindings every
update, which I think isn't a worthy tradeoff.

As to the order - they SHOULD be compatible in any order, as conflicting
files have been removed.

Thanks for getting in touch! Well keep trying to figure out the "enabled by
default" thing. :)
