### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Moamoo** [katubug/CottageWitch119#54]
**Describe the bug**
making fairy lights I cannot make any . No crafting recipes work. 

**To Reproduce**

1.put all needed items in crafting table to make any bulb in the mod of fairy lights
2.once all ingredients are in crafting table nothing happens
3. trying other recipes and bulbs do not work

**Expected behavior**
I hopped to make fairy lights even with trying other things 

**Screenshots**
![2023-10-08_00 32 42](https://github.com/katubug/CottageWitch119/assets/147294763/08e5641d-14ce-4bd5-88f8-be58c4dacb95)
![2023-10-08_00 38 19](https://github.com/katubug/CottageWitch119/assets/147294763/ed919961-46c8-4f53-a42c-115bb7e57132)

**What Cottage Witch version are you using?**
Version: 1.19.2

**Additional context**

if there's a different way to make it please tell or if I'm just slow.

**Comment by katubug** [comment]
Hi, this is an issue with the Fairy Lights mod, I am unable to fix it.
Sorry! Some people have said that the sophisticated storage crafting
upgrade grid is able to make them.

**Comment by Moamoo** [comment]
That worked thank you so much!

**Comment by katubug** [comment]
This is also fixed in the most recent version, as we replaced FastSuite with RecipeEssentials, which does not have that bug.
