### ISSUE TITLE
[Bug] Duplication glitch via Ped Beds + Crows

### ISSUE THREAD

**Issue by tali9** [katubug/CottageWitch119#55]
_**THIS APPLIES TO COTTAGE WITCH: RECAST- SORRY!**_

**Describe the bug**
The bug in question is a duplication glitch in which crows can be used to duplicate items with a pet bed.

**To Reproduce**
1. Get a Crow
2. Put an item in the Hand/Hat slot [Can literally be anything in Hand slot, Hat slot for helmets]
3. Make a crow touch a pet bed so it will respawn at it
4. Kill the Crow [Since hitting it doesn't work you can suffocate it with sand], when it dies it drops helds items
5. When  the Crow respawns it will have the held items it dropped when it died on it, duplicating said item.

**Expected behavior**
Crow dies, drops its items and respawns with nothing equipped. Alternatively doesn't drop said items and respawns with them. First option seems better in my opinion.

**Screenshots**

https://github.com/katubug/CottageWitch119/assets/20379159/27cf81d5-ab8b-4d36-9370-2ac98b298a53

**What Cottage Witch version are you using?**
Version: 1.3.2 but also persists to 1.4.0 [Checked]

**Additional context**
Very problematic in servers, as any item can be equipped in the hand slot of the Crow - From Blocks to items to armor. Imagine infinite anything! Albeit a very slow process as a crow can only hold one item at a given time, it can be easily sped up with multiple crows with pet beds.

**Comment by katubug** [comment]
I have referenced this issue in the relevant mod issue trackers, as I don't believe there's anything I can do as a modpack maker. Thanks for reporting though! Hopefully we can get it fixed!
