### ISSUE TITLE
[Bug] Wolf's Collar Tags duplicates enchantments onto unenchanted Collar Tags

### ISSUE THREAD

**Issue by tali9** [katubug/CottageWitch119#56]
_**THIS APPLIES TO COTTAGE WITCH: RECAST- SORRY!**_

**Describe the bug**
A Wolf's Collar Tags duplicates enchantments onto unenchanted Collar Tags by replacing the enchanted collar tag

**To Reproduce**
1. Get a wolf
2. Give it an enchanted collar tag [Can be any enchantment]
3. Replace the enchanted collar tag with an unenchanted collar tag
4. Enchanted collar returns, then reapply it to re-replace the unenchanted collar tag.
5. Previously unenchanted collar tag returns as enchanted

**Expected behavior**
Applying an unenchanted collar tag instead of an enchanted collar tag, then reapplying the enchanted collar tag should return an unenchanted collar tag.

**Screenshots**

https://github.com/katubug/CottageWitch119/assets/20379159/03058939-9531-4cc5-9ce3-902cefc47022

**What Cottage Witch version are you using?**
Version: 1.4.0

**Additional context**
While not too critical since you can enchant 64 collar tags without additional cost, it becomes a problem if someone severely abuses this and makes more than 64 enchanted collar tags for the price of one.

**Comment by katubug** [comment]
Hi, thank you for reporting this! If you can report this to the
Domestication Innovation mod author, they should be able to fix it! I don't
think there's anything I can personally do though.

**Comment by tali9** [comment]
Ah- I reposted it in Cottage Witch: Recast's Repository before this- Sorry!
