### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by anelmtree** [katubug/CottageWitch119#58]
**What Cottage Witch version are you using?**
Most current version, 1.15.7.

**What were you doing when you crashed?**
I was attempting to launch the modpack through the Minecraft Launcher after clicking the "play" button on the CurseForge application, and in the middle of the "preparing" loading bar, the launcher will close then reopen with the "exit code 1" error.

**To Reproduce**
1. Go to CurseForge.
2. Click on Play on the Cottage Witch modpack.
3. This opens the Minecraft Launcher, in which you'll click Play again.
4. After clicking Play, the Minecraft Launcher will close of it's own volition.
5. Minecraft Launcher re-opens, see error.

**Screenshots**
![image](https://github.com/katubug/CottageWitch119/assets/58537663/9308baeb-55cb-4679-86be-95162577f5f3)
![image](https://github.com/katubug/CottageWitch119/assets/58537663/4fb1ddf9-571f-4f80-93c1-98af2412c315)

**Crash Reports or Latest.log**
Here is the latest crash report. https://pastebin.com/ATNKN71N

**Additional context**
I have tried many of the suggested fixes, like making sure I've allocated 6-8GB of RAM, uninstalling and reinstalling both CurseForge and Minecraft, making sure my Java and drivers are up to date, and I made sure another modpack would work (I tried launching Pixelmon and it was fine). I'm kinda grasping at straws to figure out what's going wrong here.

**Comment by anelmtree** [comment]
Right now it just says “Pending Moderation” which might be why you can’t see it. I had it set to unlisted, but changed it to public in hopes that fix the problem.

**Comment by katubug** [comment]
Shoot, idk why it would be pending moderation. You could try just attaching
the file to this ticket maybe? Sorry for the trouble

**Comment by anelmtree** [comment]
No need to apologize, you're all good! I'll attach the .txt file below, let me know if you need anything else.
[hs_err_pid2924.log](https://github.com/katubug/CottageWitch119/files/13048664/hs_err_pid2924.log)

**Comment by katubug** [comment]
Okay so good news: I know exactly what's causing the crash. It's a GPU
driver issue! The downside is it's a bit tricky to fix.

I'm attaching some screenshots of the instructions per my mod, Crank. Let
me know if this helps!

**Comment by anelmtree** [comment]
Are the screenshots attached or are you working on getting them? Sorry, just want to make sure, not seeing any screenshots on my end.

**Comment by katubug** [comment]
They were supposed to be attached, but it seems GitHub doesn't work that way (I was responding via email). Let's try again!

![Screenshot_20231019-194841.png](https://github.com/katubug/CottageWitch119/assets/20935286/91e9a12c-bf8e-42f3-9328-2504fdbe0f85)

![Screenshot_20231019-194825.png](https://github.com/katubug/CottageWitch119/assets/20935286/7e31ba9c-3bf5-4095-8f0c-ab382cb96f36)

**Comment by anelmtree** [comment]
I successfully uninstalled and reinstalled the AMD Graphics drive, remove the oculus file from the mods folder, and the modpack now launches successfully! Thank you so, so much, and extend my thanks to Crank as well. I'll now be able to join my friend's server thanks to you guys, I greatly appreciate it!! <3

**Comment by katubug** [comment]
Yay, I'm glad! Sorry it took so long, but I hope you have fun!
