### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by WaffleBean3** [katubug/CottageWitch119#6]
Hello! I keep getting an error when trying to download this mod pack. It is saying "The Hammer Tools Extension and More" file missing, aborting installation. Not sure which end it is on but wanted to see if you could help. Thanks!

**Comment by katubug** [comment]
Hi, thanks for reporting!

You're not the only one having this issue, but unfortunately it's not on my
end to fix. I've never heard of the mod which is supposedly missing. :(

I have contacted Curseforge support and I'll keep you posted!

**Comment by WaffleBean3** [comment]
No worries! I am glad it is being looked into! Thanks for your help :)
