### ISSUE TITLE
[Bug] Cognition is missing from the server files

### ISSUE THREAD

**Issue by JulianVennen** [katubug/CottageWitch119#60]
**Describe the bug**
The server files are missing the mod cognition. Since this mod is included on the client, connecting to a server is not possible without further modifications.
 
**To Reproduce**
1. Download the server files
2. Start the server
3. Download the client
4. Start the client
5. Try to join the server

**Expected behavior**
The connection should be established without any problems.

**What Cottage Witch version are you using?**
Version: 1.15.12

**Comment by katubug** [comment]
Aw heck doodle, I could have sworn I got this sorted! Thanks for the
report, I'll get it fixed asap!
