### ISSUE TITLE
[Bug] Blocks not placing or placing wrong item

### ISSUE THREAD

**Issue by jordanhollyy** [katubug/CottageWitch119#61]
**Describe the bug**
Whenever I am placing blocks like stairs they do not place however some blocks can be placed but are placing a random item rather than what i am trying to build with. 
**To Reproduce**
In creative mode select birch stairs and place them,  it places something i dont know what it is but its strange.
In creative select cherry stairs and place them, they just immediately disappear.
**Expected behavior**
To be able to place an item and for it to be the correct item and to place properly
**What Cottage Witch version are you using?**
Version: Cottage Witch Recast-1.5.3

**Comment by jordanhollyy** [comment]
Hi!! Yes this is n a server hosted by ScalaCube which installed the mod
pack on the server for us and I have downloaded the mod pack from
curseforge on the latest version! Not sure if the version on ScalaCube
isn’t updated

**Comment by katubug** [comment]
Unfortunately I can't tell you what's going on without knowing what version
of the modpack is on the server. But my guess is that they just don't have
the right server pack - it should be 1.5.3 hotfix.
