### ISSUE TITLE
[Crash]: aquaculture:wooden_fillet_knife crash

### ISSUE THREAD

**Issue by CoolGo1425** [katubug/CottageWitch119#65]
### Modpack Version Used

1.16.1

### What happened?

logged on to my server with a friend for the first time, they broke a lilac and it dropped as an item and we both crashed.
im unsure whether its the item entity, a specific item or what but we both crashed and cant join our server.

(log is too big to upload fully anywhere, github gist is lagging out on me.)

**Comment by katubug** [comment]
Hi, sorry for the trouble! This is a known issue and we'll be releasing an update today to deal with it. Thank you for reporting!

**Comment by CoolGo1425** [comment]
oh sorry! i was using the wrong version of the pack serverside and the latest on client so it was crashing me for registery error since  the mod was removed.

**Comment by CoolGo1425** [comment]
closing because answer yes yes
