### ISSUE TITLE
Ender eye not working

### ISSUE THREAD

**Issue by ghostflower67** [katubug/CottageWitch119#67]
### Modpack Version Used

1.19.2

### What happened?

Every time I try to use the ender eyes it keeps saying that it doesn't want to be used and I don't know if its a bug or if im using it wrong. The only thing im doing is clicking on it and its still not working

**Comment by katubug** [comment]
Hi, this is part of the End Remastered mod. Vanilla ender eyes cannot be used, you'll need the Explorer's Compass to find the stronghold, and 12 of the End Remastered eyes to open the portal. There's more info on the eyes in the quest book!
