### ISSUE TITLE
[Bug]: Emojiful breaks Patchouli Guidebook Text Rendering

### ISSUE THREAD

**Issue by IdrisQe** [katubug/CottageWitch119#69]
### Modpack Version Used

1.16.2hotfix

### What happened?

Emojiful is known to cause bugged Patchouli rendering. This causes lines to break much earlier than they should, and then causes text to overflow as a result. The only real option is to use the text overflow "resize" mode in Patchouli, but that will then cause text to be nearly illegible on some longer pages, unless you choose "overflow" mode which makes the text just extend off the page and also be nearly illegible.

### Screenshots (if applicable)

With Emojiful:
![withemojiful](https://github.com/katubug/CottageWitch119/assets/40530630/e56d8cd2-29fa-4ae1-b3d1-ed80238ca84d)
Without Emojiful:
![withoutemojiful](https://github.com/katubug/CottageWitch119/assets/40530630/1cd4e4c8-ae1c-4706-bb67-95bdcedbddde)

**Comment by katubug** [comment]
First off, you're ticket #69 so, yanno, nice. Also thank you for bringing
this to my attention. We've been having some other issues with emojiful so
it's very possible we'll be removing it in an upcoming update.

Do you know if the mod devs have said anything about fixing this
incompatibility?

Regardless, feel free to delete it from your client in the meantime. I
don't think it will affect your ability to connect to servers with the
modpack. And thanks again for reporting!

**Comment by IdrisQe** [comment]
Sorry for the slow response! It seems the devs tried to fix this problem with the version of the mod that Cottage Witch is using, but it didn't work. https://github.com/InnovativeOnlineIndustries/Emojiful/issues/78

However, it was supposedly fixed in 1.16 (https://github.com/VazkiiMods/Patchouli/issues/306) but seems to be back.

Also Emojiful is, at least on Modrinth, both Client and Server "Required" so I'm not certain if removing it clientside will allow joining servers - though with me and the server host both removing it everything worked fine.

**Comment by sigmastar00** [comment]
Emojiful has been removed from the pack at this point, so I'm closing out this issue
