### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by WholesomeWolf** [katubug/CottageWitch119#7]
Hey, I had just found this modpack the day of posting this and really really wanna play it! It sounds so cozy and fun, but I've tried to launch the game several times and each time it crashes. It crashes before it even gets to the menu screen or while it tries to load the screen to create a new singleplayer world. I've looked through the logs but have no clue where to begin in trying to understand what it's saying. I've also never used GitHub before, so I hope doing things right to help y'all help me out. I'm including two of the several logs just in case there might be something different in each one.
[2023-03-11-4.log](https://github.com/katubug/CottageWitch119/files/10949874/2023-03-11-4.log)
[2023-03-11-3.log](https://github.com/katubug/CottageWitch119/files/10949878/2023-03-11-3.log)

**Comment by katubug** [comment]
Hi, no worries, these logs work just fine!

I don't see how much RAM you have allocated in the logs, I'm not sure
whether that means you haven't set it in your curseforge settings, or if
the logs just don't show it for some reason. But can you tell me how much
RAM you have allocated? I recommend 6-8gb if you don't have a beefy CPU.

**Comment by WholesomeWolf** [comment]
I have it set to about 7 gb now. I hadn't allocated any RAM outside of the default for curseforge beforehand. I had never really needed to mess with the RAM for modpacks before and didn't even know how to change it, so that's why I didn't think that was the problem. It's not crashing anymore now that I have it set. Thank you so much for answering quickly despite the solution being simple!

**Comment by katubug** [comment]
I'm glad to hear that fixed it! I think Curseforge's automatic settings are
good for many modpacks, depending on your pc, so it's pretty common to not
realize that setting is even there! And no problem, I'm always happy to
help :)
