### ISSUE TITLE
Please update Extended Mushrooms to 3.0.1.5 when it's available

### ISSUE THREAD

**Issue by IdrisQe** [katubug/CottageWitch119#70]
Hi, just thought I'd mention, once it's available you should update Extended Mushrooms. The version used in 1.16.2 and 1.16.3 of the modpack has a big issue that causes mega mushrooms to grow through blocks, causing a lot of damage, but it will be fixed in newer versions.

See: https://github.com/cech12/ExtendedMushrooms/issues/84#issuecomment-2042413517

Edit: It's actually already released!
https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms/files/5245900

**Comment by katubug** [comment]
Thanks for reporting this! We'll keep an eye out!

**Comment by IdrisQe** [comment]
Not critical enough to require a hotfix but just to mention, you may want to update it again to 3.0.1.6 next time the pack goes for an update. Another issue is getting fixed in that version: https://github.com/cech12/ExtendedMushrooms/issues/84#issuecomment-2043672420
