### ISSUE TITLE
Some flowers from Oh The Biomes You'll Go that are required for collection quests are not obtainable without commands

### ISSUE THREAD

**Issue by Emissaryofwind** [katubug/CottageWitch119#72]
**What Cottage Witch version are you using?**
Version: 1.15.16

**Clearly describe the issue**
The following flowers are required to complete the relevant collection quests, but the 1.19.2 version of BYG does not include any biome where these will spawn, making them impossible to obtain:

winter cyclamen
snowdrop
protea flower
daffodil (regular and pink)
california poppy
delphinium
silver vase flower
winter rose

The winter scilla is obtainable through the uncrafting table, but does not spawn naturally in the world.

**Comment by katubug** [comment]
Thank you for reporting this! We will get this changed for the upcoming version. Interesting that they keep the flowers in the mod but don't have them spawning anywhere.
