### ISSUE TITLE
[Crash] Server crashes: mobtimizations requires coroutil

### ISSUE THREAD

**Issue by JulianVennen** [katubug/CottageWitch119#74]
**What Cottage Witch version are you using?**
Version: 1.16.7

**What were you doing when you crashed?**
I attempted to start the server.

**To Reproduce**
1. Download server files
2. Run startserver.sh

**Crash Reports or Latest.log**
https://mclo.gs/aDxCcfz#L184

**Additional context**
Mobtimizations is not present on the client but included in the server files.

**Comment by katubug** [comment]
Mobtimizations is reportedly only necessary on the server. There was an
error with the first server pack where its dependency, coroutil, wasn't
present. We've released a fixed version and are waiting on curseforge to
approve it. In the meantime, please install the latest coroutil for for
1.19.2 :)
