### ISSUE TITLE
[Crash]Error code 6 after creating new world 

### ISSUE THREAD

**Issue by giacomott** [katubug/CottageWitch119#75]
**What Cottage Witch version are you using?**
Version: 1.16.7

**What were you doing when you crashed?**
I've downloaded this modpack on the CurseForge app, and when I try to create a new world, it crashes and shows me exit code 6. However, it allows me to use servers. Ive tried removing and re downloading.

**Crash Reports or Latest.log**

A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x00000001154d94e4, pid=2998, tid=109447
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# v  ~StubRoutines::SafeFetch32
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://aka.ms/minecraftjavacrashes
#

---------------  S U M M A R Y ------------

Command Line: -Djava.library.path=/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/bin/9144b457709968d9505488d99e841181e49301ad -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.24.17 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-43.3.5.jar,forge-43.3.5 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries --module-path=/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx4096m -Xms256m -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -DlibraryDirectory=/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/libraries -Dlog4j.configurationFile=/Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/assets/log_configs/client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username GiacTT --version forge-43.3.5 --gameDir /Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Instances/Cottage Witch --assetsDir /Users/giacomotiani-tanzi/Documents/curseforge/minecraft/Install/assets --assetIndex 1.19 --uuid 660c6ce28e964d2bb8538290445277cc --clientId RDIzQzczNjdDNzg2NDJERDlBOUM2RUY0NjM3OEYzMUU= --xuid 2533274938579424 --userType msa --versionType release --width 1024 --height 768 --launchTarget forgeclient --fml.forgeVersion 43.3.5 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Host: "MacBookPro17,1" arm64, 8 cores, 8G, Darwin 20.6.0, macOS 11.5.2 (20G95)
Time: Wed May 22 15:00:12 2024 BST elapsed time: 78.289534 seconds (0d 0h 1m 18s)

**Comment by katubug** [comment]
Hi, this a Mac-specific bug with a certain version of Java. You can read more about it here: https://www.reddit.com/r/fabricmc/comments/16lgix6/minecraft_crashes_when_i_open_a_world_on_macos/

Closing this because it's not something I can fix. Thanks for reporting!
