### ISSUE TITLE
Unable To Sprint

### ISSUE THREAD

**Issue by JellyPaws** [katubug/CottageWitch119#77]
I'm not sure why but I cannot sprint at all. I can crouch and lay but sprinting just doesn't work. I also can't find a FOV mod that would affect it? Thanks!

**Comment by katubug** [comment]
Hi, thanks for reporting. I believe the fov toggle is in the Accessibility settings? Those weren't intended to ship out with the update, they'll be fixed for next time. :)

**Comment by JellyPaws** [comment]
Thank you for the response but I'm still not able to sprint, even after adjusting settings and keybinds.

**Comment by katubug** [comment]
Can you please attach your latest.log?

**Comment by sigmastar00** [comment]
Some versions of the modpack had the FOV change on sprinting disabled, which caused many people to think that sprinting wasn't working. You can re-enable the FOV change from the accessibility menu. If it turns out that wasn't the problem, feel free to open another issue!
