### ISSUE TITLE
[Bug] Extreme Lag when Rendering Chunks

### ISSUE THREAD

**Issue by JellyPaws** [katubug/CottageWitch119#79]
When exploring and rendering chunks i get >4 fps and it makes it impossible to move/continue exploring.

**Comment by JellyPaws** [comment]
I believe it has to do with the follow command per the summoning staff from mythic mounts.

**Comment by wiredwhiskers** [comment]
Thanks for the heads up, this may have been resolved in recent updates due to a lot of changes with optimization mods
