### ISSUE TITLE
Shaders not working

### ISSUE THREAD

**Issue by littlek786** [katubug/CottageWitch119#82]
**What Cottage Witch version are you using?**
Version: 1.16.10

**How much RAM you have allocated (recommended 6-8gb)**
16gb

**Clearly describe the issue**
I've been trying to use shaders for the mod pack but nothing seems to be working. Tried installing optifine to the modpack to get shaders to work, but it just kept crashing anytime I tried to open it so i had to remove it, Is there a way to add shaders?

**Comment by katubug** [comment]
Yes, Oculus is already in the pack, as the description mentions! You can
just put your shaders in the shaderpacks folder :)
