### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by xJon** [katubug/CottageWitch119#83]
- **Yeetus Experimentus**
https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus
(From [ModernFix](https://www.curseforge.com/minecraft/mc-mods/modernfix)'s page) "will suppress the pop-up screen about experimental game features, which otherwise causes the game to reload its resources twice".

- **TexTrue's Embeddium Options**
https://www.curseforge.com/minecraft/mc-mods/textrues-embeddium-options
Improvements to the Video Settings menu.

- **Falling Leaves**
https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge
**Let Sleeping Dogs Lie**
https://www.curseforge.com/minecraft/mc-mods/let-sleeping-dogs-lie
Pretty and cute respectively.

- You can also consider adding [EMF](https://www.curseforge.com/minecraft/mc-mods/entity-model-features) & [ETF](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric), for compatibility with CEM resource packs such as [Fresh Animations](https://www.curseforge.com/minecraft/texture-packs/fresh-animations).

- Also just putting a suggestion for [Jade](https://www.curseforge.com/minecraft/mc-mods/jade) (+ [Jade Addons](https://www.curseforge.com/minecraft/mc-mods/jade-addons)), or [WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit-forge) (+ [Megane](https://www.curseforge.com/minecraft/mc-mods/megane-forge)), to replace [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe), as I personally find either have better aesthetics (Jade in particular).

- Lastly a note about the default graphical settings, I noticed they are all set to Fast - I assume this is intentional, but at least when spawned in I found similar if not better performance using _Fancy_, without mentioning the nicer leaves and clouds - so that might be something for you to reconsider.

https://github.com/katubug/CottageWitch119/assets/8945347/1c2f4969-7081-4ef0-89b9-16da9c6ca787

**Comment by sigmastar00** [comment]
Hi thank you for the suggestions. Feel free to make any changes you want for your personal instance, however we are not accepting mod suggestions for the modpack at this time.
