### ISSUE TITLE
[Bug] No Recipe for Sophisticated Storage Filter 

### ISSUE THREAD

**Issue by Whiskey-Kitten** [katubug/CottageWitch119#85]
**Describe the bug**
When looking at all the sophisticated storage upgrades there is a quest for filter but no recipe and no mention that you have to find the filter.

**To Reproduce**
Go to JEI and go to the sophisticated storage and backpack upgrades, you will see no filter. 

**Expected behavior**
Have a recipe for the filter. Unless the quest just needs to explain how you get it.

**Screenshots**

**What Cottage Witch version are you using?**
Version: 1.16.10

**Additional context**

**Comment by katubug** [comment]
Thank you for the report! Looks like we accidentally disabled the wrong item. We'll get it sorted ASAP, thank you for letting us know!
