### ISSUE TITLE
[Bug] Shift lock

### ISSUE THREAD

**Issue by anrchstprl** [katubug/CottageWitch119#88]
Shift key constantly being triggered when in a menu (crafting table, settings, etc)
Setting a new keybind results in shift + (key) rather than just the key.
Attempting to grab items in inventory, chest, crafting table, etc will result in it immediately moving to the next slot ie hotbar > inventory 
inventory > crafting table rather than picking up the item on the cursor.

Not entirely sure how I got this bug, i was just in a crafting table and it started happening. It's not my shift key either, it doesn't lock my shift in the chat, it doesn't lock my shift outside of  gui like settings and inventory

Version: 1.16.10

**Comment by katubug** [comment]
This is a new one for me! Have you tried restarting your whole computer? Does it persist?

**Comment by anrchstprl** [comment]
restarting pc did fix it ♥
