### ISSUE TITLE
[Crash] Game Crashes When Starting New World (Exit Code 6)

### ISSUE THREAD

**Issue by Kami-The-Foxy** [katubug/CottageWitch119#90]
**What Cottage Witch version are you using?**
Version: 1.16.11

**What were you doing when you crashed?**
Starting a new world for the first time

**To Reproduce**
1. Start Game
2. Click New World
3. No changes to any options, then click Create New World

**Screenshots**
<img width="585" alt="Screenshot 2024-08-25 at 3 43 14 PM" src="https://github.com/user-attachments/assets/f7029a3c-e9a1-4a2b-822a-0e1244a07664">

**Crash Reports or Latest.log**
[hs_err_pid32691.log](https://github.com/user-attachments/files/16741705/hs_err_pid32691.log)

**Additional context**

**Comment by katubug** [comment]
Hi, thanks for reporting! This is an issue between the latest Java for Mac,
and the mod Spark. You can learn more here:
https://www.reddit.com/r/fabricmc/s/E2CrxsUU7y
