### ISSUE TITLE
[Bug] softlocked out of a world / server!

### ISSUE THREAD

**Issue by anrchstprl** [katubug/CottageWitch119#91]
when you enter a server or a world, you are locked in the esc menu.
you CAN click 'back to game' but it won't do anything.

i'm not sure what causes it, or what fixes it. restarting the client has helped sometimes, others not so much. restarting the server falls into the same boat.

it may have some relation to tabbing out whilst loading into a world/server?

it effectively locks you out of playing the game, stuck in the menu forever until it resolves itself.

version 1.16.12, but ive noticed this happen with previous versions too.

**Comment by katubug** [comment]
This is the first time I've heard of this, but you say it's been happening on multiple versions? I'm wondering if there might be something with your setup that's causing it, such as a touchy keyboard or some sort of software issue? If you can attach your latest.log, we can have a look and see if it says anything helpful.

**Comment by anrchstprl** [comment]
[05Sep2024 16:24:02.690] [Render thread/ERROR] [com.mojang.blaze3d.audio.OpenAlUtil/]: Deleting stream buffers: Invalid operation.
[05Sep2024 16:24:02.690] [Render thread/ERROR] [com.mojang.blaze3d.audio.OpenAlUtil/]: Deleting stream buffers: Invalid operation.


is all that it says when i try to click back to game

this time when i saved and quit back to the main menu then reentered the game it fixed it.

other times it wouldnt fix if i even restarted the entire client 

🤷‍♀️

**Comment by katubug** [comment]
Can you share the whole log though? I'm not sure if I'll be able to find anything in it though, I'd bet any money this is a hardware issue of some kind. Have you tried any other modpacks?
