### ISSUE TITLE
[Crash] Server files contain client-only mod "Colorful Hearts"

### ISSUE THREAD

**Issue by JulianVennen** [katubug/CottageWitch119#92]
**What Cottage Witch version are you using?**
Version: 1.16.13

**What were you doing when you crashed?**
Starting the server included in the server files.

**To Reproduce**
1. Download the server files
2. Try to start the server
3. See error

**Crash Reports or Latest.log**
https://mclo.gs/8iWMxqM

**Additional context**
Removing the mod allows the server to start without any problems.
The mod description directly mentions that it is client-only.

**Comment by katubug** [comment]
Hi, thanks for reporting! We actually have gotten a couple reports of this, it was just due to a slip up on our end. We will be updating the modpack server pack file shortly, in the meantime, you can just delete the client side mod Colorful Hearts :)
