### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ItsJoyism** [katubug/CottageWitch119#93]
**What Cottage Witch version are you using?**
Version: 1.16.13.zip

**How much RAM you have allocated (recommended 6-8gb)**
8gb 

**Clearly describe the issue**
Was just wondering if if its normal for 1.16.13hotfix.zip to keep crashing?(exit:1) it never opened after the first time i played it and i also couldn't see my character or their hand- ;-; I ended up downloading the version before that and it works just fine but i just wanted to know if it was due to my pc or something else :)

**Screenshots**
Attach relevant screenshots here.

**Comment by katubug** [comment]
It's possible that the installation went wrong, but I haven't had any
reports of the hotfix failing to launch until now. Unfortunately, exit code
1 just means "it crashed" and I'd need a crash report from your
crash-reports folder to help figure out what was going wrong.

The invisible entities issue is a known bug with Oculus and should be fixed
by restarting your game.
