### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Blueberryfrost** [katubug/CottageWitch119#94]
So uh, the discord server for the mine craft server "Cottage Witch" Is invalid and Im unable to use the one in curse forge & in game.

**Comment by katubug** [comment]
Hmmm, which in-game one is broken? I just fixed the one in the Welcome page recently, so that one *should* work. The custom URL keeps breaking because you need max boosts for it 😭

Anyway, you can join here: https://discord.gg/zvFNa7kyXm

**Comment by Blueberryfrost** [comment]
max boosts? Anywho- it keeps saying It's invalid or I need permission to join/or it's expired

**Comment by Blueberryfrost** [comment]
![image](https://github.com/user-attachments/assets/67bbb937-9c43-483b-b49a-e43561ea05fc)

(Not sure if it worked.)

**Comment by katubug** [comment]
I double checked the one on the curseforge page and it works for me. And the one I linked just above I literally just created. I think there may be an issue with your discord account.
