### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by random-person-11** [katubug/CottageWitch119#96]
**What Cottage Witch version are you using?**
Version: 1.16.13

**What were you doing when you crashed?**
I am able to open the launcher, but when I try to create a world after a few second, it completely crashes.

**To Reproduce**
1. After a few seconds of the create world

**Crash Reports or Latest.log**

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x0000000137d354e4, pid=71291, tid=38163
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# v  ~StubRoutines::SafeFetch32
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://aka.ms/minecraftjavacrashes
#

---------------  S U M M A R Y ------------

Command Line: -Djava.library.path=/Documents/curseforge/minecraft/Install/bin/ecdf3ced54a2bf551971f768f6a82a257804cfa2 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=3.3.13 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-43.3.5.jar,forge-43.3.5 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=/Documents/curseforge/minecraft/Install/libraries --module-path=/Documents/curseforge/minecraft/Install/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/Documents/curseforge/minecraft/Install/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:/Documents/curseforge/minecraft/Install/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx4096m -Xms256m -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -DlibraryDirectory=/Documents/curseforge/minecraft/Install/libraries -Dlog4j.configurationFile=/Documents/curseforge/minecraft/Install/assets/log_configs/client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username LilaDelSol --version forge-43.3.5 --gameDir /Documents/curseforge/minecraft/Instances/Cottage Witch --assetsDir /Documents/curseforge/minecraft/Install/assets --assetIndex 1.19 --uuid 76f2931cb7f34b21acd301a6963d72ae --clientId OTMzOTUzMUVGMkY0NEE4RUJFOUY5RjUzMDY5RDgxRjQ= --xuid 2535425466433474 --userType msa --versionType release --width 1024 --height 768 --launchTarget forgeclient --fml.forgeVersion 43.3.5 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Host: "MacBookAir10,1" arm64, 8 cores, 8G, Darwin 23.5.0, macOS 14.5 (23F79)
Time: Thu Oct 17 18:54:59 2024 EDT elapsed time: 512.052641 seconds (0d 0h 8m 32s)

**Comment by katubug** [comment]
Hi there! First off, you'll probably want to update your modpack at some
point because your version is somewhat old. However, that wouldn't fix this
issue, because it's a firmware problem.

I googled your problematic frame, and found this post:
https://www.reddit.com/r/allthemods/s/0O15jqUB8G

They recommend either updating or downgrading java, or if you're not a
server owner, you can delete the Spark mod and that might fix it.
