### ISSUE TITLE
Mods seem to be missing from latest server pack

### ISSUE THREAD

**Issue by Papaturts** [katubug/CottageWitch119#97]
**Describe the bug**
Seems to be 4 mods missing from the Cottage Witch-Server-1.16.19 file
Also seems there are some kubejs errors as well after adding these mods and getting onto the server as well

**To Reproduce**
Try to install server pack via a hosting service
Start server
try to connect
Says client with the same version has mods the server does not

**Expected behavior**
To connect to the server and play without the need to add the mods

**Screenshots**

**What Cottage Witch version are you using?**
Version: 1.16.19 on both server and client

**Additional context**
![Screenshot_2024_11_11-1](https://github.com/user-attachments/assets/538c8a19-e301-4f1d-8042-62e58001f3ec)

**Comment by katubug** [comment]
This is most likely due to an incomplete installation via the host - to my
knowledge all those are included in the server pack. Have you tried
reinstalling, or contacting your host?

**Comment by Papaturts** [comment]
Ill give that a try an letcha know

**Comment by Papaturts** [comment]
The hosting service/Kinetic Hosting, redownloaded the pack to their service
I reinstalled it
Still getting the same error of missing mods on server

**Comment by Papaturts** [comment]
We were able to get it resolved.
Seems it wasnt getting loaded properly on their end.
All mods seem to be in and no script errors either
Thank you
