### ISSUE TITLE
[Crash] JEI crashing game

### ISSUE THREAD

**Issue by LeeryCoin812** [katubug/CottageWitch119#98]
**What Cottage Witch version are you using?**
Version:  1.16.19

**What were you doing when you crashed?**
Accessing recipes using the JEI, crashes for both keyboard and mouse keys on items. 

**To Reproduce**
1. Once in world enter inventory
2. either click R or U on individual item or
3. right click item in JEI
4. see crash report

**Screenshots**

**Crash Reports or Latest.log**

[crash-2024-11-15_14.09.56-client.txt](https://github.com/user-attachments/files/17770465/crash-2024-11-15_14.09.56-client.txt)

**Additional context**
I have tried restarting Minecraft launcher completely as well as computer reset and still having the crash happen.

**Comment by katubug** [comment]
Hmmm, this is an odd one! I haven't had it reported before, and it seems to
be from JEI itself. Have you checked their issue tracker to see if anything
similar has been posted?

**Comment by LeeryCoin812** [comment]
I found a couple in the github for JEI but they are saying its an almostunified problem recipe conflict or something. they said they may have fixed it in new updates so i have manually updated almost unified. Ill let you know if this fixes things.

**Comment by LeeryCoin812** [comment]
Alrighty, so i have updated almostunified and seems to have solved the issue. I tried multiple ways to activate JEI and all is good. Hopefully if anyone else reading with this issue is able to fix their game with this :)
