### ISSUE TITLE
How to set autostarting process in "run.bat"   (server modpack)

### ISSUE THREAD

**Issue by anchoriteven** [katubug/CottageWitch119#99]
**What Cottage Witch version are you using?**
Version: 1.16.19 modpackes of server 

**How much RAM you have allocated (recommended 6-8gb)**
2~8GB

**Clearly describe the issue**
I don't know how to add the auto-restarting process (in "run.bat") in the mod serverpack, the reason of  I run with "run.bat" is my Chinese server cannot pass the "version checker"(cannot connect the mirror website) and I cannot startup server with "startserver.bat", so I can only use "run.bat" and it actually can startup the server , however, I don't know how to add the auto-strating process....

**Screenshots**
Attach relevant screenshots here.

**Comment by katubug** [comment]
Hi, I'm really sorry but I'm not sure how to fix this issue. You should
contact your server host for help with the startup script.

**Comment by anchoriteven** [comment]
OK, I have been solved, thanks.
